# Generated by Django 5.2.7 on 2025-10-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='atc_code',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='brand',
        ),
        migrations.AddField(
            model_name='medicine',
            name='active_substance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='medicines/'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
