# Generated by Django 5.2.7 on 2025-10-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_remove_medicine_atc_code_remove_medicine_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='active_substance',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='description',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='image',
        ),
        migrations.AddField(
            model_name='medicine',
            name='atc_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='medicine',
            name='brand',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
