# Generated by Django 5.2.7 on 2025-10-29 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_remove_medicine_active_substance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='atc_code',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='city',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='is_24h',
        ),
        migrations.AddField(
            model_name='medicine',
            name='analogs',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='medicines/'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.medicine'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.pharmacy'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='working_hours',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
